/**
 * Challenge-09
 *  9. Reversal of Lines of a Multiline Text File
        Write a program that opens a text file and extracts its lines into a stack of strings. The 
        program should then pop the strings from the stack and save them in a second text 
        file. Thus, the first line of the first file should be ordered as the last line of the second 
        file, the second line should be ordered as the second last line, and so on.
 */

#include <iostream>
#include <fstream>
#include "../Challenge-02/Stack.h"
using namespace std;

/**
 * @brief Reverses the order of lines in a text file and saves to a new file
 * 
 * This function reads a text file line by line, stores each line in a stack,
 * then writes the lines in reverse order to a new output file. The output
 * filename is generated by inserting "-reversed" before the file extension.
 * 
 * @param fileName The name/path of the input file to reverse
 * 
 * @note Output file format: "filename-reversed.ext" (e.g., "test-reversed.txt")
 * @note If the input file has no extension, "-reversed" is appended at the end
 */
void reversalLinesOfTextFiles(const string& fileName)
{
    // Attempt to open the input file
    ifstream inputFileStream(fileName);
    if (!inputFileStream)
    {
        cerr << "Error: Unable to open input file '" << fileName << "'. Please check the file path and try again." << endl;
        return;
    }

    string line;
    Stack<string> fileContentStack;
    
    // Read each line and push onto stack (LIFO reverses order)
    while (getline(inputFileStream, line))
        fileContentStack.push(line);
    inputFileStream.close();

    // Generate output filename by inserting "-reversed" before extension
    string fullOutputFileName = fileName;
    auto index = fullOutputFileName.find('.');
    if (index != string::npos)  // Extension found
        fullOutputFileName.insert(index, "-reversed");
    else  // No extension found
        fullOutputFileName.append("-reversed");
    
    // Attempt to open the output file
    ofstream outputFileStream(fullOutputFileName);
    if (!outputFileStream)
    {
        cerr << "Error: Unable to create output file '" << fullOutputFileName << "'. Please check write permissions." << endl;
        return;
    }

    // Pop lines from stack and write to output file in reverse order
    while (!fileContentStack.isEmpty())
    {
        fileContentStack.pop(line);
        outputFileStream << line << endl;
    }
    outputFileStream.close();
    
    cout << "Success: File lines reversed and saved to '" << fullOutputFileName << "'." << endl;
}

/**
 * @brief Main entry point of the program
 * @return Exit status code (0 for success)
 */
int main(void)
{
    reversalLinesOfTextFiles("TextFile.txt");
    return 0;
}